name: Rollbar Autofix
description: Automatically opens PRs to fix Rollbar errors.
author: Rollbar
branding:
  icon: zap
  color: blue

inputs:
  openai_api_key:
    description: API key for Codex
    required: true
  rollbar_access_token:
    description: Rollbar project access token (read/write) for MCP tools
    required: true
  github_token:
    description: Token for opening GitHub PR. Use a PAT to enable running workflows. Or leave blank to use GITHUB_TOKEN.
    required: false
    default: ''
  item_counter:
    description: Rollbar item counter (e.g., 123456)
    required: true
  environment:
    description: Rollbar environment (e.g., staging, production)
    required: false
    default: unknown
  language:
    description: Project language hint (e.g. node|python|go|java)
    required: false
    default: unknown
  test_command:
    description: Command to execute tests
    required: false
    default: ''
  lint_command:
    description: Command to execute lints
    required: false
    default: ''
  max_iterations:
    description: Max fix iterations
    required: false
    default: '1'
  pr_base:
    description: Base branch for PR to be created
    required: false
    default: 'main'

outputs:
  summary:
    description: Markdown summary of what the agent did
  branch_name:
    description: Suggested branch name for the PR
  pr_title:
    description: Pull request title generated by the agent (with fallback)
  pr_body:
    description: Pull request body generated by the agent (including appended repro script)

runs:
  using: node20
  main: dist/index.js
